### ISSUE TITLE
TODO grafica 

### ISSUE THREAD

**Issue by MarcoPrina** [MarcoLagalla/marette_backend#79]
- [x] Attaccare l'immagine nelle carte dei ristoranti (quelle sulla home) se non ricordo male è .image

- [x] Mostrare l'immagine di profilo nel profilo utente
- [x] Ovunque si deve caricare un immagine (registrazione ristorante, registrazione utente normale e business, menu) quando scorri il box dell'immagine rimane sopra la barra superiore del menù

- [x] Nella carta prodotto hai messo un pulsante con un "%", non sapevo a cosa servisse e l'ho lasciato ma non sembra molto intuitivo

- [x] Modalità cellulare 

- [x] Menù per attivare i componenti non trasparenti ma in barra laterale a destra sitile profilo vecchio (chiedi che ti spieghiamo)

- [x] Componente BannerValidateEmail presente nella pagina profilo da rendere bello

------------Home - Galleria----------------

- [x] Quando aggiungi un immagine si apre un popup che è da rendere carino

- [x] Dare un occhiata in generale alla grafica dei due componenti

------------Vetrina----------------
- [x] Aggiungi menù ora ha una dimensione fissa, non diventa più super lungo, modificalo a tuo piacimento 

- [x] Quand aggiungo un menù o faccio delle modifiche faccio comparire con un alert un messaggi popup, vedi tu se ti piace o se lo vuoi eliminare/modificare

- [x] I menù del giorno ora sono più complicati, prova ad aggiungere una portata,  quando devi aggiungere i prodotti ti mostra un menù a tendina dove puoi selezionarli solo che poi devi cliccare da un altra parte per chiudere il menù a tendina, non mi garba tantissimo questa cosa se ti viene in mentre altro provaci, se no lascia così ed amen

- [x] Le carte dei prodotti nelle portate mi sembrano troppo grosse e troppo vicine fra loro, vedi se riesci a modificarle 

- [x] Se aggiungi più di una portata la carta del menù diventa troppo corta, io non userei la scroll bar come avevi fatto in precedenza ma lascerei che la carta si adatti al contenuto. Se sono un cliente che va sulla home di un ristorante non voglio dover scroollare dentro una carta per vedere il menù del giorno, piuttosto scrollo la pagina
