### ISSUE TITLE
TODO: parte operativa grafica

### ISSUE THREAD

**Issue by MarcoPrina** [MarcoLagalla/marette_backend#96]
- [x] Mettere a posto modifica dati ristorante

- [x] Modificare immagine profilo

- [x] Guardare per sessionid (viene creato da Django Admin quando ci si collega.)

- [x] Errore utente non esiste rimane anche dopo aver chiuso login e sulla registrazione

- [x] Il profilo non si carica se apro marette direttamente da lui
